//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhatsNext.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Approach
    {
        public long Id { get; set; }
        public long FKUser { get; set; }
        public Nullable<System.DateTime> EventTime { get; set; }
    
        public virtual User User { get; set; }
    }
}
