//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhatsNext.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Content
    {
        public long Id { get; set; }
        public string ImgUrl { get; set; }
        public string MainTextLeft { get; set; }
        public string MainTextRight { get; set; }
        public string TitleLeft { get; set; }
        public string TitleRight { get; set; }
        public string Message1Left { get; set; }
        public string Message1Right { get; set; }
        public string Message2Left { get; set; }
        public string Message2Right { get; set; }
        public string Message3Left { get; set; }
        public string Message3Right { get; set; }
        public string Message4Left { get; set; }
        public string Message4Right { get; set; }
        public Nullable<int> Duration { get; set; }
        public Nullable<int> Animation { get; set; }
        public string Display { get; set; }
        public string MediaType { get; set; }
        public string Friends { get; set; }
        public string Interests { get; set; }
    }
}
