//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhatsNext.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Interest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Interest()
        {
            this.Interests1 = new HashSet<Interest>();
            this.Users_Interests = new HashSet<Users_Interests>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public Nullable<long> FKInterest { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Interest> Interests1 { get; set; }
        public virtual Interest Interest1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Users_Interests> Users_Interests { get; set; }
    }
}
